// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AppSummary struct {
	Name            string               `json:"name"`
	Frontdoor       string               `json:"frontdoor"`
	Path            string               `json:"path"`
	Provider        *string              `json:"provider,omitempty"`
	DefaultModel    *string              `json:"defaultModel,omitempty"`
	EnableResponses bool                 `json:"enableResponses"`
	ModelRouting    *ModelRoutingSummary `json:"modelRouting,omitempty"`
}

type Divergence struct {
	Type        DivergenceType `json:"type"`
	Path        string         `json:"path"`
	Description string         `json:"description"`
	Primary     map[string]any `json:"primary,omitempty"`
	Shadow      map[string]any `json:"shadow,omitempty"`
}

type DivergentShadowsResponse struct {
	// Interactions with divergent shadow results (these are regular interaction summaries)
	Interactions []InteractionSummary `json:"interactions"`
	Total        int                  `json:"total"`
	Limit        int                  `json:"limit"`
	Offset       int                  `json:"offset"`
}

type FrontdoorSummary struct {
	Type         string  `json:"type"`
	Path         string  `json:"path"`
	Provider     *string `json:"provider,omitempty"`
	DefaultModel *string `json:"defaultModel,omitempty"`
}

type Interaction struct {
	ID                  string               `json:"id"`
	TenantID            string               `json:"tenantId"`
	Frontdoor           string               `json:"frontdoor"`
	Provider            string               `json:"provider"`
	AppName             *string              `json:"appName,omitempty"`
	RequestedModel      string               `json:"requestedModel"`
	ServedModel         *string              `json:"servedModel,omitempty"`
	ProviderModel       *string              `json:"providerModel,omitempty"`
	Streaming           bool                 `json:"streaming"`
	Status              string               `json:"status"`
	Duration            string               `json:"duration"`
	DurationNs          int64                `json:"durationNs"`
	Metadata            map[string]any       `json:"metadata,omitempty"`
	RequestHeaders      map[string]any       `json:"requestHeaders,omitempty"`
	CreatedAt           int64                `json:"createdAt"`
	UpdatedAt           int64                `json:"updatedAt"`
	Request             *InteractionRequest  `json:"request,omitempty"`
	Response            *InteractionResponse `json:"response,omitempty"`
	Error               *InteractionError    `json:"error,omitempty"`
	TransformationSteps []TransformationStep `json:"transformationSteps,omitempty"`
	Shadows             []ShadowResult       `json:"shadows,omitempty"`
}

type InteractionConnection struct {
	Interactions []InteractionSummary `json:"interactions"`
	Total        int                  `json:"total"`
}

type InteractionError struct {
	Type    string  `json:"type"`
	Code    *string `json:"code,omitempty"`
	Message string  `json:"message"`
}

type InteractionEvent struct {
	ID                 string         `json:"id"`
	InteractionID      string         `json:"interactionId"`
	Stage              string         `json:"stage"`
	Direction          string         `json:"direction"`
	APIType            *string        `json:"apiType,omitempty"`
	Frontdoor          *string        `json:"frontdoor,omitempty"`
	Provider           *string        `json:"provider,omitempty"`
	AppName            *string        `json:"appName,omitempty"`
	ModelRequested     *string        `json:"modelRequested,omitempty"`
	ModelServed        *string        `json:"modelServed,omitempty"`
	ProviderModel      *string        `json:"providerModel,omitempty"`
	ThreadKey          *string        `json:"threadKey,omitempty"`
	PreviousResponseID *string        `json:"previousResponseId,omitempty"`
	Raw                map[string]any `json:"raw,omitempty"`
	Canonical          map[string]any `json:"canonical,omitempty"`
	Headers            map[string]any `json:"headers,omitempty"`
	Metadata           map[string]any `json:"metadata,omitempty"`
	CreatedAt          string         `json:"createdAt"`
}

type InteractionEventsResponse struct {
	InteractionID string             `json:"interactionId"`
	Events        []InteractionEvent `json:"events"`
}

type InteractionFilter struct {
	// Filter by frontdoor type (openai, anthropic, responses)
	Frontdoor *string `json:"frontdoor,omitempty"`
	// Filter by provider name
	Provider *string `json:"provider,omitempty"`
	// Filter by status
	Status *string `json:"status,omitempty"`
}

type InteractionRequest struct {
	Raw             map[string]any `json:"raw,omitempty"`
	Canonical       map[string]any `json:"canonical,omitempty"`
	UnmappedFields  []string       `json:"unmappedFields,omitempty"`
	ProviderRequest map[string]any `json:"providerRequest,omitempty"`
}

type InteractionResponse struct {
	Raw            map[string]any `json:"raw,omitempty"`
	Canonical      map[string]any `json:"canonical,omitempty"`
	UnmappedFields []string       `json:"unmappedFields,omitempty"`
	ClientResponse map[string]any `json:"clientResponse,omitempty"`
	FinishReason   *string        `json:"finishReason,omitempty"`
	Usage          *Usage         `json:"usage,omitempty"`
}

type InteractionSummary struct {
	ID                 string         `json:"id"`
	Type               string         `json:"type"`
	Status             *string        `json:"status,omitempty"`
	Model              *string        `json:"model,omitempty"`
	Metadata           map[string]any `json:"metadata,omitempty"`
	MessageCount       *int           `json:"messageCount,omitempty"`
	PreviousResponseID *string        `json:"previousResponseId,omitempty"`
	CreatedAt          int64          `json:"createdAt"`
	UpdatedAt          int64          `json:"updatedAt"`
}

type MemoryStats struct {
	Alloc      int64 `json:"alloc"`
	TotalAlloc int64 `json:"totalAlloc"`
	Sys        int64 `json:"sys"`
	NumGc      int   `json:"numGC"`
}

type ModelRewriteSummary struct {
	ModelExact  *string `json:"modelExact,omitempty"`
	ModelPrefix *string `json:"modelPrefix,omitempty"`
	Provider    string  `json:"provider"`
	Model       string  `json:"model"`
}

type ModelRoutingSummary struct {
	PrefixProviders map[string]any        `json:"prefixProviders,omitempty"`
	Rewrites        []ModelRewriteSummary `json:"rewrites,omitempty"`
}

type Overview struct {
	Mode       string             `json:"mode"`
	Storage    *StorageSummary    `json:"storage"`
	Apps       []AppSummary       `json:"apps"`
	Frontdoors []FrontdoorSummary `json:"frontdoors"`
	Providers  []ProviderSummary  `json:"providers"`
	Routing    *RoutingSummary    `json:"routing"`
	Tenants    []TenantSummary    `json:"tenants"`
}

type ProviderSummary struct {
	Name              string  `json:"name"`
	Type              string  `json:"type"`
	BaseURL           *string `json:"baseUrl,omitempty"`
	SupportsResponses bool    `json:"supportsResponses"`
	EnablePassthrough bool    `json:"enablePassthrough"`
}

type Query struct {
}

type RoutingRule struct {
	ModelPrefix *string `json:"modelPrefix,omitempty"`
	ModelExact  *string `json:"modelExact,omitempty"`
	Provider    string  `json:"provider"`
}

type RoutingSummary struct {
	DefaultProvider string        `json:"defaultProvider"`
	Rules           []RoutingRule `json:"rules"`
}

type ShadowError struct {
	Type    string  `json:"type"`
	Code    *string `json:"code,omitempty"`
	Message string  `json:"message"`
}

type ShadowRequest struct {
	Canonical       map[string]any `json:"canonical,omitempty"`
	ProviderRequest map[string]any `json:"providerRequest,omitempty"`
}

type ShadowResponse struct {
	Raw            map[string]any `json:"raw,omitempty"`
	Canonical      map[string]any `json:"canonical,omitempty"`
	ClientResponse map[string]any `json:"clientResponse,omitempty"`
	FinishReason   *string        `json:"finishReason,omitempty"`
	Usage          *ShadowUsage   `json:"usage,omitempty"`
}

type ShadowResult struct {
	ID                      string          `json:"id"`
	InteractionID           string          `json:"interactionId"`
	ProviderName            string          `json:"providerName"`
	ProviderModel           *string         `json:"providerModel,omitempty"`
	Request                 *ShadowRequest  `json:"request,omitempty"`
	Response                *ShadowResponse `json:"response,omitempty"`
	Error                   *ShadowError    `json:"error,omitempty"`
	DurationNs              int64           `json:"durationNs"`
	TokensIn                *int            `json:"tokensIn,omitempty"`
	TokensOut               *int            `json:"tokensOut,omitempty"`
	Divergences             []Divergence    `json:"divergences,omitempty"`
	HasStructuralDivergence bool            `json:"hasStructuralDivergence"`
	CreatedAt               int64           `json:"createdAt"`
}

type ShadowResultsResponse struct {
	InteractionID string         `json:"interactionId"`
	Shadows       []ShadowResult `json:"shadows"`
}

type ShadowUsage struct {
	PromptTokens     *int `json:"promptTokens,omitempty"`
	CompletionTokens *int `json:"completionTokens,omitempty"`
	TotalTokens      *int `json:"totalTokens,omitempty"`
}

type Stats struct {
	Uptime       string       `json:"uptime"`
	GoVersion    string       `json:"goVersion"`
	NumGoroutine int          `json:"numGoroutine"`
	Memory       *MemoryStats `json:"memory"`
}

type StorageSummary struct {
	Enabled bool    `json:"enabled"`
	Type    string  `json:"type"`
	Path    *string `json:"path,omitempty"`
}

type TenantSummary struct {
	ID             string `json:"id"`
	Name           string `json:"name"`
	ProviderCount  int    `json:"providerCount"`
	RoutingRules   int    `json:"routingRules"`
	SupportsTenant bool   `json:"supportsTenant"`
}

type TransformationStep struct {
	Stage       string         `json:"stage"`
	Description string         `json:"description"`
	Before      map[string]any `json:"before,omitempty"`
	After       map[string]any `json:"after,omitempty"`
}

type Usage struct {
	InputTokens  *int `json:"inputTokens,omitempty"`
	OutputTokens *int `json:"outputTokens,omitempty"`
	TotalTokens  *int `json:"totalTokens,omitempty"`
}

type DivergenceType string

const (
	DivergenceTypeMissingField DivergenceType = "MISSING_FIELD"
	DivergenceTypeExtraField   DivergenceType = "EXTRA_FIELD"
	DivergenceTypeTypeMismatch DivergenceType = "TYPE_MISMATCH"
	DivergenceTypeArrayLength  DivergenceType = "ARRAY_LENGTH"
	DivergenceTypeNullMismatch DivergenceType = "NULL_MISMATCH"
)

var AllDivergenceType = []DivergenceType{
	DivergenceTypeMissingField,
	DivergenceTypeExtraField,
	DivergenceTypeTypeMismatch,
	DivergenceTypeArrayLength,
	DivergenceTypeNullMismatch,
}

func (e DivergenceType) IsValid() bool {
	switch e {
	case DivergenceTypeMissingField, DivergenceTypeExtraField, DivergenceTypeTypeMismatch, DivergenceTypeArrayLength, DivergenceTypeNullMismatch:
		return true
	}
	return false
}

func (e DivergenceType) String() string {
	return string(e)
}

func (e *DivergenceType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DivergenceType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DivergenceType", str)
	}
	return nil
}

func (e DivergenceType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DivergenceType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DivergenceType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
